"""Initial migration: create tables

Revision ID: b30351627035
Revises:
Create Date: 2022-04-04 18:03:36.078767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b30351627035'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'component',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('cad_model_link', sa.String(), nullable=True),
        sa.Column('vendor_code', sa.String(), nullable=True),
        sa.Column('supplier_name', sa.String(), nullable=True),
        sa.Column('weight', sa.Float(precision=5), nullable=True),
        sa.Column('price', sa.Float(precision=3), nullable=True),
        sa.Column('extra_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_component_id'), 'component', ['id'], unique=False)
    op.create_table(
        'group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('is_set', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['group.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_table(
        'vehicle',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('extra_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_table(
        'feature',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_feature_id'), 'feature', ['id'], unique=False)
    op.create_table(
        'function',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('feature_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_function_id'), 'function', ['id'], unique=False)
    op.create_table(
        'vehicle_features',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.Integer(), nullable=True),
        sa.Column('feature_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['feature_id'], ['feature.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('vehicle_id', 'feature_id')
    )
    op.create_index(op.f('ix_vehicle_features_id'), 'vehicle_features', ['id'], unique=False)
    op.create_table(
        'vehicle_configuration',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.Integer(), nullable=True),
        sa.Column('component_id', sa.Integer(), nullable=True),
        sa.Column('function_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['component_id'], ['component.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['function_id'], ['function.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('vehicle_id', 'function_id', 'component_id')
    )
    op.create_index(op.f('ix_vehicle_configuration_id'), 'vehicle_configuration', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_configuration_id'), table_name='vehicle_configuration')
    op.drop_table('vehicle_configuration')
    op.drop_index(op.f('ix_vehicle_features_id'), table_name='vehicle_features')
    op.drop_table('vehicle_features')
    op.drop_index(op.f('ix_function_id'), table_name='function')
    op.drop_table('function')
    op.drop_index(op.f('ix_feature_id'), table_name='feature')
    op.drop_table('feature')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_component_id'), table_name='component')
    op.drop_table('component')
    # ### end Alembic commands ###
