FROM python:3.10.2

COPY . /vehicle_builder
WORKDIR /vehicle_builder

RUN python -m pip install --upgrade pip && python -m pip install -r ./requirements.txt --no-cache-dir
RUN chmod +x /vehicle_builder/docker/run.sh

CMD ["/vehicle_builder/docker/run.sh"]
